name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2

    - name: Set up Firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
    - run:  |
        which chromedriver
        chromedriver --version
        which chrome
        chrome --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test selenium
      run: |
        python -m pytest -v -s ./testcase/test_github_pipeline.py

    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        browser: 'chrome'
        robot_tests_dir: ./testcase/

#    - name: Test robot
#      run: |
#        which python
#        robot ./testcase/TC2.robot

